# Generated by Django 3.0.4 on 2020-03-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20200330_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Sale', 'sale'), ('Rent', 'rent')], max_length=10),
        ),
    ]
